package resources;

import gameplay.TileTypes;

public enum Resource {
	
	TEXTURE_TILE_BRICK,
	TEXTURE_TILE_DESERT,
	TEXTURE_TILE_FOREST,
	TEXTURE_TILE_SHEEP,
	TEXTURE_TILE_STONE,
	TEXTURE_TILE_WHEAT,
	
	TEXTURE_CARD_BRICK,
	TEXTURE_CARD_FOREST,
	TEXTURE_CARD_SHEEP,
	TEXTURE_CARD_STONE,
	TEXTURE_CARD_WHEAT,
	
	TEXTURE_CARD_KNIGHT,
	
	TEXTURE_BOARD,
	
	TEXTURE_TABLE,
	
	TEXTURE_COLOR_BLUE,
	TEXTURE_COLOR_RED,
	TEXTURE_COLOR_YELLOW,
	TEXTURE_COLOR_GREEN,
	TEXTURE_COLOR_PURPLE,
	TEXTURE_COLOR_WHITE,
	
	TEXTURE_SKYBOX,
	
	MESH_TILE,
	MESH_ROAD,
	MESH_SETTLEMENT,
	MESH_CITY,
	MESH_ROBBER,
	MESH_BOARD,
	MESH_GUI,
	MESH_SKYBOX,
	MESH_TABLE,
	
	MODEL_TILE_BRICK,
	MODEL_TILE_DESERT,
	MODEL_TILE_FOREST,
	MODEL_TILE_SHEEP,
	MODEL_TILE_STONE,
	MODEL_BOARD,
	MODEL_TABLE,
	MODEL_TILE_WHEAT;
	
	public static Resource getTileModel(TileTypes t) {
		return switch (t) {
			case BRICK -> MODEL_TILE_BRICK;
			case DESERT -> MODEL_TILE_DESERT;
			case FOREST -> MODEL_TILE_FOREST;
			case STONE -> MODEL_TILE_STONE;
			case WHEAT -> MODEL_TILE_WHEAT;
			case SHEEP -> MODEL_TILE_SHEEP;
		};
	}
}
